import Head from "next/head";
import * as S from "./styles";

export default function Home() {
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.ContainerGlobal>
        <S.MainContainer>
          <S.WrapperSteps>OI</S.WrapperSteps>
          <S.WrapperForm>Olá</S.WrapperForm>
        </S.MainContainer>
      </S.ContainerGlobal>
    </>
  );
}
